Set min SDK for libraries/textlayoutbuilder
Summary:
D59400937 removes this provided_dep:
https://www.internalfb.com/code/fbsource/[a19276126fa24704db0a110484ab3f11d2012b88]/fbandroid/libraries/textlayoutbuilder/library/src/main/java/com/facebook/fbui/textlayoutbuilder/BUCK?lines=6-8

and replaces it with an explicit dep on `androidx:core`. The dep shouldn't have been provided in the first place. Now that it's a regular dep, this manifest requires an explicit min SDK >= core's min SDK, otherwise:
```
Error: /data/sandcastle/boxes/fbsource/fbandroid/libraries/textlayoutbuilder/library/src/main/AndroidManifest.xml Error:
uses-sdk:minSdkVersion 1 cannot be smaller than version 19 declared in library /data/sandcastle/boxes/fbsource/buck-out/v2/gen/fbsource/3d23920a9b9e4d39/third-party/java/androidx/core/core/1.13.1-patched/__core-aar__/AndroidManifest.xml
Suggestion: use tools:overrideLibrary="androidx.core" to force usage
Exception in thread "main" com.facebook.buck.core.exceptions.HumanReadableException: Error generating manifest file
at com.facebook.buck.android.manifest.GenerateManifest.mergeManifests(GenerateManifest.java:134)
at com.facebook.buck.android.manifest.GenerateManifest.generateXml(GenerateManifest.java:67)
at com.facebook.buck.android.manifest.GenerateManifestExecutableMain.run(GenerateManifestExecutableMain.java:85)
at com.facebook.buck.android.manifest.GenerateManifestExecutableMain.main(GenerateManifestExecutableMain.java:62)
```

I believe all apps using this are min SDK 21 anyway.

Reviewed By: xiphirx

Differential Revision: D59599612

fbshipit-source-id: f6873b6f635aec0b93620a30a74f1c0c5fcc7743